# Generated by Django 4.2.30 on 2026-05-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('cloud_provider', models.CharField(max_length=100)),
                ('account_id', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('usage', models.FloatField()),
                ('cost', models.FloatField()),
                ('currency', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=100)),
                ('environment', models.CharField(max_length=100)),
            ],
        ),
    ]
