# Generated by Django 4.2.30 on 2026-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cloudcost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudcost',
            old_name='usage',
            new_name='usage_value',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='default_user', max_length=100),
            preserve_default=False,
        ),
    ]
