# Generated by Django 4.2.30 on 2026-05-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_usage_cloudcost_usage_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloudCost',
        ),
    ]
