# Generated by Django 4.2.30 on 2026-05-14 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('date', models.DateField()),
                ('cloud_provider', models.CharField(max_length=100)),
                ('account_id', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('usage', models.FloatField()),
                ('cost', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=100)),
                ('environment', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cloudwise_cloudcost',
            },
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
