# Generated by Django 4.2.30 on 2026-05-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_selection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.AlterField(
            model_name='cloudcost',
            name='client_id',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='cloudcost',
            table='cloudwise_cloudcost',
        ),
    ]
